export const GET_ALL_BUSINESSES = 'GET_ALL_BUSINESSES';
export const CREATE_BUSINESS = 'CREATE_BUSINESS';
export const UPDATE_BUSINESS = 'UPDATE_BUSINESS';
export const DELETE_BUSINESS = 'DELETE_BUSINESS';
export const GET_BUSINESS = 'GET_BUSINESS';

export const GET_ALL_PERSONS = 'GET_ALL_PERSONS';
export const CREATE_PERSON = 'CREATE_PERSON';
export const UPDATE_PERSON = 'UPDATE_PERSON';
export const DELETE_PERSON = 'DELETE_PERSON';

export const START_FETCH = 'START_FETCH';
export const FAIL_FETCH = 'FAIL_FETCH';

export const RESTART_RENDER = 'RESTART_RENDER';
